target_folder = "../target"
threads = 64
filetype = "nrrd"

# This is the fixed valoume for the initial rigid stage only
fixed_volume = "20131025_CBX2_E14.5_12.1g_WT_XY_rec_scaled_6.8627_pixel_13.nrrd"

# Set to 'true' to for population average creation
generate_new_target_each_stage = true

skip_transform_inversion = true
staging = 'none'


[[registration_stage_params]]
stage_id = "rigid"

[registration_stage_params.elastix_parameters]
Metric = "AdvancedMattesMutualInformation"
Registration = "MultiResolutionRegistration"
MaximumNumberOfIterations = 400
NumberOfResolutions = 4
NumberOfSpatialSamples = 20000
Transform = "EulerTransform"
SP_a = [ 1000.0, 1000.0, 500.0, 500.0,]
SP_alpha = 0.602
SP_A = 50.0
UseDifferentiableOverlap = "false"

[[registration_stage_params]]
stage_id = "similarity"
[registration_stage_params.elastix_parameters]
Registration = "MultiResolutionRegistration"
NumberOfResolutions = 4
Transform = "SimilarityTransform"
Metric = "AdvancedMattesMutualInformation"
MaximumNumberOfIterations = 500
NumberOfSpatialSamples = 20000

[[registration_stage_params]]
stage_id = "affine"
[registration_stage_params.elastix_parameters]
Registration = "MultiResolutionRegistration"
NumberOfResolutions = 4
Transform = "AffineTransform"
Metric = "AdvancedMattesMutualInformation"
MaximumNumberOfIterations = 500
NumberOfSpatialSamples = 20000


##################### Deformable registration stages
[[registration_stage_params]]
stage_id = "deformable_128"
[registration_stage_params.elastix_parameters]
Registration = "MultiResolutionRegistration"
NumberOfResolutions = 1
NumberOfSpatialSamples = 200000
MaximumStepLength = 3.0
NumberOfGradientMeasurements = 10
NumberOfSamplesForExactGradient = 20000
NumberOfJacobianMeasurements = 4000
MaximumNumberOfIterations = 250
AutomaticParameterEstimation = "true"
UseAdaptiveStepSizes = "true"
ASGDParameterEstimationMethod = "DisplacementDistribution"
Transform = "BSplineTransform"
Metric = "AdvancedMattesMutualInformation"
FinalGridSpacingInVoxels = 128


[[registration_stage_params]]
stage_id = "deformable_64"
inherit_elx_params = "deformable_128"
[registration_stage_params.elastix_parameters]
FinalGridSpacingInVoxels = 64



[[registration_stage_params]]
stage_id = "deformable_32"
inherit_elx_params = "deformable_128"
[registration_stage_params.elastix_parameters]
MaximumStepLength = 2.0
FinalGridSpacingInVoxels = 32


[[registration_stage_params]]
stage_id = "deformable_16"
inherit_elx_params = "deformable_32"
[registration_stage_params.elastix_parameters]
NumberOfResolutions = 1
Metric = [ "AdvancedMattesMutualInformation", "TransformBendingEnergyPenalty",]
Registration = "MultiMetricMultiResolutionRegistration"
FinalGridSpacingInVoxels = 16
MaximumStepLength = 1.0
Metric0Weight = 1.0
Metric1Weight = 50


[[registration_stage_params]]
stage_id = "deformable_8"
inherit_elx_params = "deformable_16"
[registration_stage_params.elastix_parameters]
MaximumStepLength = 1.0
FinalGridSpacingInVoxels = 8


######## End deforamble registration


[global_elastix_params]
FixedInternalImagePixelType = "float"
MovingInternalImagePixelType = "float"
FixedImageDimension = 3
MovingImageDimension = 3
UseDirectionCosines = "true"
FixedImagePyramid = "FixedSmoothingImagePyramid"
MovingImagePyramid = "MovingSmoothingImagePyramid"
ResultImagePixelType = "short"
ResultImageFormat = "nrrd"
CompressResultImage = "true"
Interpolator = "BSplineInterpolator"
ResampleInterpolator = "FinalBSplineInterpolator"
Resampler = "DefaultResampler"
NumberOfHistogramBins = 32
HowToCombineTransforms = "Compose"
NewSamplesEveryIteration = "true"
ImageSampler = "RandomCoordinate"
FinalBSplineInterpolationOrder = 3
BSplineInterpolationOrder = 3
DefaultPixelValue = 0
WriteTransformParametersEachIteration = "false"
WriteTransformParametersEachResolution = "true"
WriteResultImage = "true"
WriteResultImageAfterEachResolution = "true"
AutomaticScalesEstimation = "true"
AutomaticTransformInitialization = "true"
Optimizer = "AdaptiveStochasticGradientDescent"
UseRandomSampleRegion = "false"
